[package]
name = "portfolio-contact-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-sns = "0.10"
aws-config = "0.10"
lambda_http = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
